### ISSUE TITLE
Add explanation of cookiecutter variable overrides to the README.md

### ISSUE THREAD

**Issue by snapp** [snapp/template-ansible-collection#11]
Explain how cookiecutter variable defaults can be silently overridden using `~/.cookiecutterrc` or explicitly overridden by passing a yaml configuration file at runtime via the `--config-file` parameter.

Both approaches just need a `default_context` section with the overrides defined similar to this example:
```
---
default_context:
  author: "snapp@example.com"
  namespace: "snapp"
```
